[2025-01-30T11:02:41.584+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-30T11:02:41.731+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: model_pipeline.run_pipeline manual__2025-01-30T11:02:34.996566+00:00 [queued]>
[2025-01-30T11:02:41.841+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: model_pipeline.run_pipeline manual__2025-01-30T11:02:34.996566+00:00 [queued]>
[2025-01-30T11:02:41.996+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2025-01-30T11:02:42.016+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): run_pipeline> on 2025-01-30 11:02:34.996566+00:00
[2025-01-30T11:02:42.106+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'model_pipeline', 'run_pipeline', 'manual__2025-01-30T11:02:34.996566+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/hw_dag.py', '--cfg-path', '/tmp/tmpferesx4s']
[2025-01-30T11:02:42.110+0000] {standard_task_runner.py:105} INFO - Job 20: Subtask run_pipeline
[2025-01-30T11:02:42.105+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=78) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-30T11:02:42.115+0000] {standard_task_runner.py:72} INFO - Started process 95 to run task
[2025-01-30T11:02:42.294+0000] {task_command.py:467} INFO - Running <TaskInstance: model_pipeline.run_pipeline manual__2025-01-30T11:02:34.996566+00:00 [running]> on host 6a16f98cbe4b
[2025-01-30T11:02:42.494+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='model_pipeline' AIRFLOW_CTX_TASK_ID='run_pipeline' AIRFLOW_CTX_EXECUTION_DATE='2025-01-30T11:02:34.996566+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-30T11:02:34.996566+00:00'
[2025-01-30T11:02:42.565+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-01-30T11:02:42.567+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-01-30T11:02:42.568+0000] {logging_mixin.py:190} INFO - Current task name:run_pipeline state:running start_date:2025-01-30 11:02:41.817718+00:00
[2025-01-30T11:02:42.570+0000] {logging_mixin.py:190} INFO - Dag name:model_pipeline and current dag run status:running
[2025-01-30T11:02:42.571+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-30T11:02:42.688+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/modules/pipeline.py", line 71, in pipeline
    df = pd.read_csv(f'{path}/data/train/homework.csv')
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 948, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 611, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1448, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1705, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
             ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/vadme/airflow_hw//data/train/homework.csv'
[2025-01-30T11:02:42.860+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-01-30T11:02:42.947+0000] {logging_mixin.py:190} INFO - Task start:2025-01-30 11:02:41.817718+00:00 end:2025-01-30 11:02:42.860076+00:00 duration:1.042358
[2025-01-30T11:02:42.956+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): run_pipeline> dag:<DAG: model_pipeline> dagrun:<DagRun model_pipeline @ 2025-01-30 11:02:34.996566+00:00: manual__2025-01-30T11:02:34.996566+00:00, state:running, queued_at: 2025-01-30 11:02:35.046660+00:00. externally triggered: True>
[2025-01-30T11:02:42.968+0000] {logging_mixin.py:190} INFO - Failure caused by [Errno 2] No such file or directory: 'C:/Users/vadme/***_hw//data/train/homework.csv'
[2025-01-30T11:02:42.979+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=model_pipeline, task_id=run_pipeline, run_id=manual__2025-01-30T11:02:34.996566+00:00, execution_date=20250130T110234, start_date=20250130T110241, end_date=20250130T110242
[2025-01-30T11:02:43.040+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-30T11:02:43.044+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 20 for task run_pipeline ([Errno 2] No such file or directory: 'C:/Users/vadme/airflow_hw//data/train/homework.csv'; 95)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/modules/pipeline.py", line 71, in pipeline
    df = pd.read_csv(f'{path}/data/train/homework.csv')
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 948, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 611, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1448, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1705, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
             ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/vadme/airflow_hw//data/train/homework.csv'
[2025-01-30T11:02:43.062+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-01-30T11:02:43.090+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-30T11:02:43.093+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
